from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _c_string(value: str) -> str:
    escaped = value.encode("ascii", errors="backslashreplace").decode("ascii")
    return '"' + escaped.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _c_optional_string(value: str | None) -> str:
    return "NULL" if value is None else _c_string(value)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the native card catalog header from local card data.")
    parser.add_argument("--sdk-path", type=Path, default=Path("data/official"))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("ptcg/native_core/ptcg_card_catalog.generated.h"),
    )
    args = parser.parse_args(argv)

    sdk_path = args.sdk_path.resolve()
    if str(sdk_path) not in sys.path:
        sys.path.insert(0, str(sdk_path))
    from cg.api import all_card_data
    from cg.api import all_attack

    cards = sorted(all_card_data(), key=lambda card: card.cardId)
    attacks = sorted(all_attack(), key=lambda attack: attack.attackId)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by scripts/generate_native_card_catalog.py. Do not edit by hand. */",
        "#ifndef PTCG_CARD_CATALOG_GENERATED_H",
        "#define PTCG_CARD_CATALOG_GENERATED_H",
        "",
        "typedef struct PtcgCardCatalogEntry {",
        "    int card_id;",
        "    int card_type;",
        "    int hp;",
        "    int basic;",
        "    int stage1;",
        "    int stage2;",
        "    int energy_type;",
        "    int retreat_cost;",
        "    int weakness_type;",
        "    int resistance_type;",
        "    int ex;",
        "    int mega_ex;",
        "    const char *evolves_from;",
        "    int attack_count;",
        "    int attacks[2];",
        "    const char *name;",
        "} PtcgCardCatalogEntry;",
        "",
        "typedef struct PtcgAttackCatalogEntry {",
        "    int attack_id;",
        "    int damage;",
        "    int energy_count;",
        "    int energies[5];",
        "    const char *name;",
        "} PtcgAttackCatalogEntry;",
        "",
        "static const PtcgCardCatalogEntry PTCG_CARD_CATALOG[] = {",
    ]
    for card in cards:
        attack_ids = list(card.attacks[:2])
        attack_ids.extend([0] * (2 - len(attack_ids)))
        lines.append(
            "    {"
            f"{card.cardId}, "
            f"{int(card.cardType)}, "
            f"{card.hp}, "
            f"{1 if card.basic else 0}, "
            f"{1 if card.stage1 else 0}, "
            f"{1 if card.stage2 else 0}, "
            f"{int(card.energyType)}, "
            f"{card.retreatCost}, "
            f"{-1 if card.weakness is None else int(card.weakness)}, "
            f"{-1 if card.resistance is None else int(card.resistance)}, "
            f"{1 if card.ex else 0}, "
            f"{1 if card.megaEx else 0}, "
            f"{_c_optional_string(card.evolvesFrom)}, "
            f"{len(card.attacks)}, "
            f"{{{', '.join(str(attack_id) for attack_id in attack_ids)}}}, "
            f"{_c_string(card.name)}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            f"static const int PTCG_CARD_CATALOG_COUNT = {len(cards)};",
            "",
            "static const PtcgAttackCatalogEntry PTCG_ATTACK_CATALOG[] = {",
        ]
    )
    for attack in attacks:
        energies = [int(energy) for energy in attack.energies[:5]]
        energies.extend([0] * (5 - len(energies)))
        lines.append(
            "    {"
            f"{attack.attackId}, "
            f"{attack.damage}, "
            f"{len(attack.energies)}, "
            f"{{{', '.join(str(energy) for energy in energies)}}}, "
            f"{_c_string(attack.name)}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            f"static const int PTCG_ATTACK_CATALOG_COUNT = {len(attacks)};",
            "",
            "#endif",
            "",
        ]
    )
    args.output.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {args.output} with {len(cards)} cards")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
